#!/usr/bin/env python

import sys

from fuse3 import FUSE
from hitagifs import HitagiOps

if len(sys.argv) != 2:
    print('usage: %s <mountpoint>' % sys.argv[0])
    sys.exit(1)
fuse = FUSE(HitagiOps(), sys.argv[1], foreground=True)

# vim: set ft=python:
